/* Tiago Madeira 76321 - Diogo Duarte 77645 */

--Callen

/* TABLE CREATION */
/*
CREATE SCHEMA CALLEN;
go
*/

CREATE TABLE G_CALLEN.COLLECTIONTYPE(
	T_ID INT IDENTITY(1,1) PRIMARY KEY,
	T_Designation VARCHAR(50) NOT NULL
);
go

CREATE TABLE G_CALLEN.COLLECTION(
	Collection_ID INT IDENTITY(1,1) PRIMARY KEY,
	Collection_Name VARCHAR(50) NOT NULL,
	Collection_Descr VARCHAR(150) NOT NULL,
	Collection_Type INT REFERENCES G_CALLEN.COLLECTIONTYPE(T_ID) NOT NULL
);
go

CREATE TABLE G_CALLEN.ARQUIVE(
	Arquive_ID INT IDENTITY(1,1) PRIMARY KEY, 
	Code VARCHAR(50) NOT NULL, 	--codigo na pasta fisica, primary key??
	Theme_Descr VARCHAR(50),
);
go

CREATE TABLE G_CALLEN.ENTITY(
	Entity_ID INT IDENTITY(1,1) PRIMARY KEY,
	Entity_Name VARCHAR(50) NOT NULL,
	Email VARCHAR(150),
	Phone VARCHAR(15)
);
go

CREATE TABLE G_CALLEN.ADDRESS(
	Address_ID INT IDENTITY(1,1) PRIMARY KEY,
	Street VARCHAR(150),
	City VARCHAR(50),
	State VARCHAR(50),
	Country VARCHAR(50),
	PostalCode VARCHAR(50)
);
go

CREATE TABLE G_CALLEN.ENTITYADRESS(
	Entity INT REFERENCES G_CALLEN.ENTITY(Entity_ID),
	Address INT REFERENCES G_CALLEN.ADDRESS(Address_ID)
	PRIMARY KEY (Entity, Address)
);
go

CREATE TABLE G_CALLEN.SPONSOR(
	Sponsor_ID INT REFERENCES G_CALLEN.ENTITY(Entity_ID) PRIMARY KEY,
	Website VARCHAR(100)
);
go

CREATE TABLE G_CALLEN.PEER(
	Peer_ID INT REFERENCES G_CALLEN.ENTITY(Entity_ID) PRIMARY KEY,
	QuantityOffered INT
);
go

CREATE TABLE G_CALLEN.SERIES(
	Series_ID INT IDENTITY(1,1) PRIMARY KEY,
	Series_Name VARCHAR(50) NOT NULL,
	Descr VARCHAR(255) NOT NULL,
);
go

--Theme atribute - folder
CREATE TABLE G_CALLEN.ITEM(
	Item_ID INT IDENTITY(1,1) PRIMARY KEY,
	Item_Name VARCHAR(100) NOT NULL,
	Item_Descr VARCHAR(255) NOT NULL,
	Item_Year VARCHAR(10) NOT NULL,
	Other VARCHAR(255),
	Type VARCHAR(50) NOT NULL, --callendar, coin...
	Sponsor INT REFERENCES G_CALLEN.SPONSOR(Sponsor_ID)
);
go

CREATE TABLE G_CALLEN.SERIESITEMS(
	Series INT REFERENCES G_CALLEN.SERIES(Series_ID),	
	Item INT REFERENCES G_CALLEN.ITEM(Item_ID),
	NumberInSeries INT,
	PRIMARY KEY(Series, Item)
);
go

CREATE TABLE G_CALLEN.INST(
	Inst_Number INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Item_ID INT REFERENCES G_CALLEN.ITEM(Item_ID),
	Note VARCHAR(150) NOT NULL,
	Favorite Bit,
	Inst_PicPath VARCHAR(255),
	Date_Insert DATETIME,
	Date_Mod DATETIME,
	Date_View DATETIME,
	State Bit, -- 0 - Belongs to Colection | 1 - Gifted
	Arquive INT REFERENCES G_CALLEN.ARQUIVE(Arquive_ID),
	Peer INT REFERENCES G_CALLEN.PEER(Peer_ID)
);
go

CREATE TABLE G_CALLEN.INSTINCOLLECTION(
	Inst INT REFERENCES G_CALLEN.INST(Inst_number),
	Collection INT REFERENCES G_CALLEN.COLLECTION(Collection_ID),
	PRIMARY KEY (Inst, Collection)
);
go

CREATE TABLE G_CALLEN.GIFT(
	Gift_ID INT IDENTITY(1,1) PRIMARY KEY,
	Peer INT REFERENCES G_CALLEN.PEER(Peer_ID),
	Item INT REFERENCES G_CALLEN.ITEM(Item_ID),
	Gift_Date DATE,
	Offered bit 
);
go

CREATE TABLE G_CALLEN.GIFTINST(
	Gift INT REFERENCES G_CALLEN.GIFT(Gift_ID) PRIMARY KEY,
	Inst INT REFERENCES G_CALLEN.INST(Inst_number)
);
go